-- 1.
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;

-- 2.
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.'
FROM TB_DEPARTMENT;

-- 3.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 4.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 5.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE department_no IS NULL;

-- 6.
SELECT *
FROM tb_student
WHERE department_no IS NULL;

-- 7.
SELECT CLASS_NO
FROM TB_CLASS
WHERE preattending_class_no IS NOT NULL;

-- 8.
SELECT DISTINCT CATEGORY
FROM tb_department;

-- 9.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM tb_student
WHERE student_address LIKE '%전주%' 
    AND ABSENCE_YN='N'
    AND EXTRACT(YEAR FROM ENTRANCE_DATE) = '2002';