CREATE TABLE SAMPLE (
    ID NUMBER,
    PWD VARCHAR2(30)
);
INSERT INTO SAMPLE VALUES(1, 'pass01');

SELECT * FROM TJOEUN.EMPLOYEE;

INSERT INTO TJOEUN.EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO, JOB_CODE)
            VALUES(401, '아무개','201212-1385769','J2');
            
            
            