-- 03.BASIC
-- 3
SELECT STUDENT_NAME
  FROM TB_STUDENT
WHERE  STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC;

-- 7
SELECT CLASS_NO
 FROM TB_CLASS
WHERE preattending_class_no IS NOT NULL; 

-- 9
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
 FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%'
   AND ABSENCE_YN = 'N'
   AND EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002
ORDER BY  STUDENT_NAME;  

-- 04.FUNCTION
-- 3.
SELECT PROFESSOR_NAME,  EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
 FROM tb_professor
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;

-- 12.
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도 별 평점"
 FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 년도;